const MAX_NUM_OF_POINTS = 100000;
const MIN_NUM_OF_POINTS = 1000;
const INITIAL_NUM_OF_POINTS = 50000;

const MIN_POS_BOUND = -1000;
const MAX_POS_BOUND = 1000;

const MAX_POINT_SIZE = 20;
const MIN_POINT_SIZE = 0.01;
const INITIAL_POINT_SIZE = 2;

const DEFAULT_POINT_COLOR = "#ba3a2c";
const CANVAS_COLOR = "#181818";

const Constant = {
    MAX_NUM_OF_POINTS,
    MIN_NUM_OF_POINTS,
    INITIAL_NUM_OF_POINTS,
    MIN_POS_BOUND,
    MAX_POS_BOUND,
    MAX_POINT_SIZE,
    MIN_POINT_SIZE,
    INITIAL_POINT_SIZE,
    DEFAULT_POINT_COLOR,
    CANVAS_COLOR
};

export default Constant;